// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13mJXAnoGuGpxtYS62pDMPi7rb97SD28',
    appId: '1:579635449675:web:789574ca44bf58b41fe2ce',
    messagingSenderId: '579635449675',
    projectId: 'testvideo-88882',
    authDomain: 'testvideo-88882.firebaseapp.com',
    storageBucket: 'testvideo-88882.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgcax9LTDbiTYqslGi6spDGD49we6T2Q8',
    appId: '1:579635449675:android:0bf68714936e07511fe2ce',
    messagingSenderId: '579635449675',
    projectId: 'testvideo-88882',
    storageBucket: 'testvideo-88882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA05KMufzsONQi9jzroJ8fKOnsLCRgekCY',
    appId: '1:579635449675:ios:48a1e947b7c6abcc1fe2ce',
    messagingSenderId: '579635449675',
    projectId: 'testvideo-88882',
    storageBucket: 'testvideo-88882.firebasestorage.app',
    iosClientId:
        '579635449675-lcfnjhkdjm2vlssm2tdjq1si6jp78ig2.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA05KMufzsONQi9jzroJ8fKOnsLCRgekCY',
    appId: '1:579635449675:ios:48a1e947b7c6abcc1fe2ce',
    messagingSenderId: '579635449675',
    projectId: 'testvideo-88882',
    storageBucket: 'testvideo-88882.firebasestorage.app',
    iosClientId:
        '579635449675-lcfnjhkdjm2vlssm2tdjq1si6jp78ig2.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC13mJXAnoGuGpxtYS62pDMPi7rb97SD28',
    appId: '1:579635449675:web:01f280a86f7dcf421fe2ce',
    messagingSenderId: '579635449675',
    projectId: 'testvideo-88882',
    authDomain: 'testvideo-88882.firebaseapp.com',
    storageBucket: 'testvideo-88882.firebasestorage.app',
  );
}
